apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL-Enedis
    type: postgres
    access: proxy
    uid: postgres-enedis
    url: postgres:5432
    user: enedis
    secureJsonData:
      password: enedis_password
    jsonData:
      database: enedis_db
      sslmode: disable
      postgresVersion: 1600
    editable: false
