[package]
name = "enedis-fuzz"
version = "0.1.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.enedis-rs]
path = ".."
features = ["xml"]
default-features = false

[[bin]]
name = "xml_parser"
path = "fuzz_targets/xml_parser.rs"
test = false
doc = false
